# Configure base class modifiers
ARTI_MOD = 1
BARB_MOD = 1
BARD_MOD = 1
CLER_MOD = 1
DRUI_MOD = 1
FIGH_MOD = 1
MONK_MOD = 1
PALA_MOD = 1
RANG_MOD = 1
ROGU_MOD = 1
SORC_MOD = 1
WARL_MOD = 1
WIZA_MOD = 1

# Specific Mods
SURGE_MOD = 0.25
EXTRA_ATTACK_MOD = 0.25
RECKLESS_MOD = 0.25
SMITE_MOD = 0.25
STUN_STRIKE_MOD = 0.25